name: quark_web
description: "Deja el desarrollo en nuestras manos, enfócate en crecer."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.2.1
  visibility_detector: ^0.4.0+2
  carousel_slider: ^5.0.0
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  cloud_firestore: ^5.5.1
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/isotipo.png'
  platforms:
    web:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/isotipo.png
    - assets/isologo.png
    - assets/misc/office.png
    - assets/services/mobile_app.png
    - assets/services/web_development.png
    - assets/services/software_development.png
    - assets/portfolio/janodanihugoproyect.png
    - assets/favicon.jpeg
    - assets/tools/awsLogo.png
    - assets/tools/dartLogo.png
    - assets/tools/firebaseLogo.png
    - assets/tools/flutterLogo.png
    - assets/tools/androidLogo.png
    - assets/tools/iosLogo.png
    - assets/tools/pythonLogo.webp
    - assets/misc/en.png
    - assets/misc/es.png
    - assets/misc/amongus_crewmate.png
    - assets/portfolio/eventosspa.png